import { defineConfig } from "vite";
import { VitePWA } from "vite-plugin-pwa";

/** Static local-first PWA build. SW generated by Workbox via vite-plugin-pwa.
 *  Update checks are manual-only (Settings → Check for updates) and updates
 *  are applied only when no workout is active (see sw-register.ts). */
export default defineConfig({
  base: "./",
  build: {
    outDir: "dist",
    target: "es2022",
    cssCodeSplit: false,
    sourcemap: false,
    reportCompressedSize: true,
  },
  define: {
    __APP_VERSION__: JSON.stringify(process.env.npm_package_version ?? "0.1.0"),
  },
  plugins: [
    VitePWA({
      strategies: "generateSW",
      registerType: "prompt", // we decide when to apply updates
      injectRegister: null, // we import virtual:pwa-register ourselves
      manifest: false, // public/manifest.webmanifest stays the single source
      includeAssets: ["manifest.webmanifest", "icons/*.png"],
      devOptions: { enabled: false }, // no SW in dev, matching old behavior
      workbox: {
        navigateFallback: "index.html",
        cleanupOutdatedCaches: true,
        // Notification-tap relay (see public/sw-notifications.js); runs inside
        // the generated worker alongside Workbox's precache routing.
        importScripts: ["sw-notifications.js"],
      },
    }),
  ],
});
